# Generated by Django 3.1.5 on 2021-08-25 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='body',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='title',
            new_name='shopname',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='categories',
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ManyToManyField(related_name='activity', to='blog.Category'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='picture/'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='activity',
            name='state',
        ),
        migrations.AddField(
            model_name='activity',
            name='state',
            field=models.ManyToManyField(related_name='activity', to='blog.State'),
        ),
    ]
