# Generated by Django 3.1.5 on 2021-08-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210825_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hiring',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
