# Generated by Django 3.1.5 on 2021-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210825_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='descriptions',
            field=models.CharField(max_length=4000),
        ),
    ]
