# Generated by Django 3.1.5 on 2021-08-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sopdetail',
            new_name='Sop_detail',
        ),
    ]
