# Generated by Django 3.1.5 on 2021-08-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0002_auto_20210825_0645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sop_detail',
            new_name='Sopdetail',
        ),
    ]
