# Generated by Django 3.1.5 on 2021-08-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0003_auto_20210825_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopdetail',
            name='Description_market_unvaccinated',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_religion_unvaccinated',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_shopping_unvaccinated',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_transport_unvaccinated',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_travel_unvaccinated',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
