# Generated by Django 3.1.5 on 2021-08-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0004_auto_20210825_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_dining_vaccinated',
            new_name='Description_dining',
        ),
    ]
