# Generated by Django 3.1.5 on 2021-08-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0005_auto_20210825_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sopdetail',
            name='Description_dining_unvaccinated',
        ),
        migrations.RemoveField(
            model_name='sopdetail',
            name='Description_market_unvaccinated',
        ),
        migrations.RemoveField(
            model_name='sopdetail',
            name='Description_religion_unvaccinated',
        ),
        migrations.RemoveField(
            model_name='sopdetail',
            name='Description_shopping_unvaccinated',
        ),
        migrations.RemoveField(
            model_name='sopdetail',
            name='Description_transport_unvaccinated',
        ),
        migrations.RemoveField(
            model_name='sopdetail',
            name='Description_travel_unvaccinated',
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='vaccine',
            field=models.BooleanField(default=False),
        ),
    ]
