# Generated by Django 3.1.5 on 2021-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0006_auto_20210825_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_transport',
            new_name='Description_arts',
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_gathering',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_health',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_meetings',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_recreational',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_school',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_sports',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_taxi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_visits',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
