# Generated by Django 3.1.5 on 2021-08-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0007_auto_20210825_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopdetail',
            name='Description_others_n',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sopdetail',
            name='Description_others_y',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_sub', models.CharField(max_length=200)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sop.sopdetail')),
            ],
        ),
    ]
