# Generated by Django 3.1.5 on 2021-08-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0008_auto_20210825_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Others',
        ),
    ]
