# Generated by Django 3.1.5 on 2021-08-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0009_delete_others'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_arts',
            new_name='Description_Arts',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_dining',
            new_name='Description_Dine_in',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_health',
            new_name='Description_Health',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_market',
            new_name='Description_House_Visiting',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_meetings',
            new_name='Description_Market',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_recreational',
            new_name='Description_Meeting',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_religion',
            new_name='Description_Receation',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_school',
            new_name='Description_Religious',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_shopping',
            new_name='Description_School',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_sports',
            new_name='Description_Shop',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_taxi',
            new_name='Description_Sports',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_travel',
            new_name='Description_Taxi',
        ),
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_visits',
            new_name='Description_Travel',
        ),
    ]
