# Generated by Django 3.1.5 on 2021-08-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0010_auto_20210825_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sopdetail',
            old_name='Description_Receation',
            new_name='Description_Recreation',
        ),
    ]
